###################################
##  Notifies me via IFTTT when something goes down.
###################################

- alias: 'Device Status'
  hide_entity: True
  trigger:
       - platform: state
         entity_id:
           - sensor.wii
           - sensor.Hue_Hub_1
           - sensor.Hue_Hub_2
           - sensor.tablotv
           - sensor.alexa_echo
           - sensor.amazon_dot
           - sensor.circle
           - sensor.rachio
           - sensor.skybell
           - sensor.printer
           - sensor.chromecast_audio_1
           - sensor.chromecast_audio_2
           - sensor.nest_upstairs
           - sensor.nest_downstairs
           - sensor.cisco_ap
           - sensor.actiontechap
           - sensor.trendnetap
           - sensor.unifi_ap
           - sensor.small_garage
           - sensor.large_garage
           - sensor.rgb_led_garage_large
           - sensor.rgb_led_garage_small
           - sensor.rgb_led_outdoor_den
           #- sensor.withings_scale
           - sensor.smart_water_meter
           - sensor.sleep_number_bed
           - sensor.nodemcu1
           - sensor.nodemcu2
           - sensor.nodemcu3
           - sensor.carlopihole
         to: 'offline'
         for:
           minutes: 5

  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Device Status:'
        value2: "{{ trigger.to_state.attributes.friendly_name }} is "
        value3: "{{ trigger.to_state.state }}"

    - service: script.speech_engine
      data_template:
        value1: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
