- platform: template
    sensors:
      wii:
          friendly_name: 'Wii U'
          value_template: "{{ 'Online' if is_state('device_tracker.wii', 'home') else 'Offline' }}"

      unifi_ap:
          friendly_name: 'Unifi AP'
          value_template: "{{ 'Online' if is_state('device_tracker.unifi_ap', 'home') else 'Offline' }}"

      rachio:
          friendly_name: 'Rachio Sprinklers'
          value_template: "{{ 'Online' if is_state('device_tracker.rachio', 'home') else 'Offline' }}"

      skybell:
          friendly_name: 'Skybell Doorbell'
          value_template: "{{ 'Online' if is_state('device_tracker.skybell', 'home') else 'Offline' }}"

      samsungtv:
          friendly_name: 'Samsung TV'
          value_template: "{{ 'Online' if is_state('device_tracker.samsungtv', 'home') else 'Offline' }}"
