#sabnzbd
- platform: sabnzbd
  name: SABnzbd
  api_key: !secret sab_key
  host: !secret sab_url
  monitored_variables:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'
