###################################
##  LOG IFTTT Stuff - [SkyBell HD](http://amzn.to/2dcexIB)
###################################

- alias: 'Log SkyBell Pressed Activity'
  hide_entity: True
  trigger:
    - platform: event
      event_type: skybell_pressed
  
  action:
    - service: script.skybell_pressed
  

