#####################################################################################
###  If the Kitchen Lights go on for more than 10 minutes, turn off the accent lights
### connected to [Etekcity Outlets](http://amzn.to/2efNoBP)
## [433Mhz Transmitter and receiver](http://amzn.to/2dceNY2)
#####################################################################################

- alias: Kitchen lights on - Accent lights off
  trigger:
    - platform: state
      entity_id: group.kitchen_lights
      to: 'on'
      for: '00:05:00'

  condition:
    - condition: state
      entity_id: switch.kitchen_accents
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_accents

##############################################################################

- alias: Kitchen lights off - turn on Accent lights
  trigger:
    - platform: state
      entity_id: group.kitchen_lights
      to: 'off'
      for: '00:05:00'

  condition:
    - condition: sun
      after: 'sunset'
    - condition: time
      before: '23:00:00'
    - condition: state
      entity_id: group.interior_lights
      state: 'on'

  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_accents
