###################################
##  Late Night lights Section -
# This is not needed once https://github.com/home-assistant/home-assistant/issues/6342 is fixed.
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################
- alias: 'Late Night Helper outside closer'
  trigger:
    - platform: state
      entity_id: group.all_covers
      to: 'closed'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: group.all_covers
        state: 'closed'

  action:
#    - service: scene.turn_on
#      entity_id: scene.front_full_brightness
    - service: script.monthly_color_scene
