#-------------------------------------------
#  Fire Tablet Alarm Panel -
#  http://www.vmwareinfo.com/2017/07/visualizing-smart-home-using-home.html
#-------------------------------------------
#
homeassistant:
  customize_glob:
    "sensor.alarm_panel_*":
      emulated_hue: False
      hidden: False
  customize:
    group.fire_tablet:
      emulated_hue: False
      hidden: True

#---Sensor for Fire Tablet-----------------------------
sensor:
  - platform: mqtt
    state_topic: "wallpanel/alarm 1/sensor/battery"
    name: "Alarm Panel 1 Battery Level"
    value_template: '{{ value_json.value }}'
    unit_of_measurement: '%'
    device_class: power

  - platform: mqtt
    state_topic: "wallpanel/alarm 1/sensor/battery"
    name: "Alarm Panel 1 Plugged In"
    value_template: '{{ value_json.acPlugged }}'
    device_class: power

  - platform: mqtt
    state_topic: "wallpanel/alarm 1/sensor/motion"
    name: "Alarm Panel 1 Motion"
    value_template: '{{ value_json.value }}'
    device_class: motion

group:
  fire_tablet:
    entities:
      - sensor.alarm_panel_1_battery_level
      - sensor.alarm_panel_1_motion
      - sensor.alarm_panel_1_plugged_in
    
