######################################################################################################
# Nest Protect Package
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# - Write up- http://www.vmwareinfo.com/2017/06/psa-check-out-your-smoke-detectors-once.html
######################################################################################################
#-----------------------------------
homeassistant:
  customize:

    binary_sensor.hallway_nest_protect_kids_hallway_online:
      friendly_name: Kids Hallway Protect
      icon: mdi:nest-protect

    binary_sensor.logans_room_nest_protect_online:
      friendly_name: Logans Room Protect
      icon: mdi:nest-protect

    binary_sensor.kitchen_nest_protect_online:
      friendly_name: Kitchen Protect
      icon: mdi:nest-protect

    binary_sensor.master_bedroom_nest_protect_online:
      friendly_name: Master Bedroom Protect
      icon: mdi:nest-protect

    binary_sensor.master_hallway_nest_protect_online:
      friendly_name: Master Hallway Protect
      icon: mdi:nest-protect

    binary_sensor.kylies_room_nest_protect_paiges_room_online:
      friendly_name: Kylies Room Protect
      icon: mdi:nest-protect

    binary_sensor.office_nest_protect_online:
        friendly_name: Office Protect
        icon: mdi:nest-protect

    group.protects:
      homebridge_hidden: true
#-------------------------------------------

#-------------------------------------------
group:
  protects:
    entities:
      - binary_sensor.upstairs_living_room_nest_protect_online
      - binary_sensor.hallway_nest_protect_kids_hallway_online
      - binary_sensor.logans_room_nest_protect_online
      - binary_sensor.kitchen_nest_protect_online
      - binary_sensor.master_bedroom_nest_protect_online
      - binary_sensor.master_hallway_nest_protect_online
      - binary_sensor.kylies_room_nest_protect_paiges_room_online
      - binary_sensor.office_nest_protect_online

#-------------------------------------------
automation:
  - alias: Nest protect emergency
    hide_entity: true
    trigger:
      platform: state
      entity_id:
        - sensor.hallway_nest_protect_kids_hallway_smoke_status
        - sensor.hallway_nest_protect_kids_hallway_co_status
        - sensor.logans_room_nest_protect_smoke_status
        - sensor.logans_room_nest_protect_co_status
        - sensor.kitchen_nest_protect_smoke_status
        - sensor.kitchen_nest_protect_co_status
        - sensor.master_bedroom_nest_protect_smoke_status
        - sensor.master_bedroom_nest_protect_co_status
        - sensor.office_nest_protect_smoke_status
        - sensor.office_nest_protect_co_status
        - sensor.kylies_room_nest_protect_paiges_room_smoke_status
        - sensor.kylies_room_nest_protect_paiges_room_co_status
      to: 'Emergency'

    condition:
      - condition: state
        entity_id: group.family
        state: 'home'

    action:
      - service: script.emergency
        data_template:
          call_garage_open: 1
