      ###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunset Stuff off'
  trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'

  action:
    - delay: '00:{{ (range(1, 55)|random|int) }}:00'
    - service: light.turn_off
      entity_id:
        - group.exterior_lights
        - group.outdoor_front_lights
        - group.outdoor_pool_lights
        - group.all_lights
    - service: script.interior_off
    - service: homeassistant.turn_off
      entity_id:
        - group.landscaping

    - service: input_boolean.turn_off
      entity_id: input_boolean.medicine
