      ###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunset Stuff on'
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'


  action:
    - service: switch.turn_on
      entity_id:
        - switch.front_door_outlet
        - switch.living_room_outlet
        - switch.den_outlet
        - switch.foyer_outlet
    - service: light.turn_on
      entity_id:
        - group.living_room_accents
    - service: light.turn_on
      data:
        entity_id:
          - light.outdoor_bathroom
        brightness: 35
    - delay: '00:{{ (range(1, 20)|random|int) }}:00'
    - service: homeassistant.turn_on
      entity_id:
        - group.landscaping
    - service: script.monthly_color_scene
    - service: script.speech_engine
      data:
        call_dark_outside: 1
        call_garage_check: 1
        call_window_check: 1
